package com.bestbuy.search.merchandising.jobs;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.solr.client.solrj.response.QueryResponse;
import org.apache.solr.common.SolrDocumentList;
import org.apache.solr.common.util.NamedList;

import com.bestbuy.search.merchandising.domain.Attribute;
import com.bestbuy.search.merchandising.domain.AttributeValue;

/**
 * The base test case for jobs
 * 
 * @author a948063
 *
 */
public class BaseJobTest {
	/**
	 * Method to get query response
	 * 
	 * @return QueryResponse
	 */
	protected QueryResponse getQueryResponse(boolean noFacetFields) {
		QueryResponse queryResponse = new QueryResponse();

		// Set response with solr document list
		NamedList<Object> responseNamedList = new NamedList<Object>();
		responseNamedList.add("response", this.getEmptySolrDocumentList());

		// Set facet information
		NamedList<Object> facetList = this.getFacetFieldList(noFacetFields);
		responseNamedList.add("facet_counts", facetList);

		queryResponse.setResponse(responseNamedList);
		return queryResponse;
	}
	
	/**
	 * Method to get an empty solr document list
	 * 
	 * @return SolrDocumentList
	 */
	private SolrDocumentList getEmptySolrDocumentList() {
		SolrDocumentList solrDocumentList = new SolrDocumentList();
		solrDocumentList.setStart(0);
		solrDocumentList.setNumFound(0);
		return solrDocumentList;
	}

	/**
	 * Method to get facet fields
	 * 
	 * @return NamedList<Object>
	 */
	protected NamedList<Object> getFacetFieldList(boolean noFacetFields) {
		NamedList<Object> facetFieldList = new NamedList<Object>();
		NamedList<NamedList<Number>> facetFields = new NamedList<NamedList<Number>>();

		if (noFacetFields) {
			facetFieldList.add("facet_fields", null);
		} else {
			// Add category facets
			Map<String, NamedList<Number>> catField = new HashMap<String, NamedList<Number>>();
			NamedList<Number> catFieldValues = new NamedList<Number>();
			catFieldValues.add("Movies", 7);
			catFieldValues.add("Entertainment", 2);
			catFieldValues.add("Music", 1);
			catField.put("junitcategory_facet", catFieldValues);
			facetFields.addAll(catField);
	
			// Add brand facets
			Map<String, NamedList<Number>> brandField = new HashMap<String, NamedList<Number>>();
			NamedList<Number> brandFieldValues = new NamedList<Number>();
			brandFieldValues.add("Agptek", 2);
			brandFieldValues.add("Centon", 2);
			brandFieldValues.add("Lowepro", 2);
			brandFieldValues.add("Netgear", 2);
			brandFieldValues.add("Tribeca", 2);
			brandField.put("junitbrand_facet", brandFieldValues);
			facetFields.addAll(brandField);
	
			// Add dnd collection facets
			Map<String, NamedList<Number>> dndField = new HashMap<String, NamedList<Number>>();
			NamedList<Number> dndFieldValues = new NamedList<Number>();
			dndFieldValues.add("On Sale", 2);
			dndFieldValues.add("Free Shipping", 2);
			dndFieldValues.add("Special Offers", 2);
			dndField.put("junitcurrentoffers_facet", dndFieldValues);
			facetFields.addAll(dndField);
			
			// Add invalid categories facet
			Map<String, NamedList<Number>> categoriesFacet = new HashMap<String, NamedList<Number>>();
			NamedList<Number> categoriesFacetValues = new NamedList<Number>();
			categoriesFacetValues.add("Home", 2);
			categoriesFacet.put("categories_facet", categoriesFacetValues);
			facetFields.addAll(categoriesFacet);
		
			facetFieldList.add("facet_fields", facetFields);
		}
		return facetFieldList;
	}
	
	/**
	 * Method to get attribute object
	 * 
	 * @param attributeName
	 * @param isActive
	 * @param attributeValue
	 * @return Attribute
	 */
	protected Attribute getAttributeObject(String attributeName, String isActive, List<AttributeValue> attributeValue) {
		Attribute object = new Attribute();
		object.setAttributeName(attributeName);
		object.setIsActive(isActive);
		object.setAttributeValue(attributeValue);
		return object;
	}
	
	/**
	 * Method to get attribute value object
	 * 
	 * @param attributeValue
	 * @param isActive
	 * @param attribute
	 * @return AttributeValue
	 */
	protected AttributeValue getAttributeValueObject(String attributeValue, String isActive, Attribute attribute) {
		AttributeValue object = new AttributeValue();
		object.setAttributeValue(attributeValue);
		object.setIsActive(isActive);
		object.setAttribute(attribute);
		return object;
	}
	
	/**
	 * Method to get dummy attribute value data
	 * 
	 * @return List<String>
	 */
	protected List<String> getDummyAttributeValueData() {
		List<String> s = new ArrayList<String>();
		s.add("Junit20th Century Fox");
		s.add("Junit2S Toner");
		s.add("Junit2SToner");
		s.add("Junit360 Electrical");
		s.add("Junit3Bays");
		s.add("Junit3C4G");
		s.add("Junit3Com");
		s.add("Junit3D Video Wizard");
		s.add("Junit3Dconnexion");
		s.add("Junit3M");
		s.add("Junit3drumsticks");
		s.add("Junit3ware");
		s.add("Junit4D CityScape");
		s.add("Junit4D Cityscape");
		s.add("Junit4D Concepts");
		s.add("Junit4D Master");
		s.add("Junit4M");
		s.add("Junit4XEM");
		s.add("Junit5* Commercial");
		s.add("Junit5.11");
		s.add("Junit72-9301");
		s.add("JunitA+ ChildSupply");
		s.add("JunitA. Saks");
		s.add("JunitA.A. Importing");
		s.add("JunitAAMP");
		s.add("JunitAAMP OF AMERICA, INC");
		s.add("JunitAAMP OF AMERICA, INC 011");
		s.add("JunitAAXA");
		s.add("JunitAAXA Technologies");
		s.add("JunitABBYY");
		s.add("JunitABC");
		s.add("JunitABLE PLANET INC");
		s.add("JunitACCO BRANDS");
		s.add("JunitACHLA Designs");
		s.add("JunitACP - Memory Upgrades");
		s.add("JunitACP EP");
		s.add("JunitACR Electronics");
		s.add("JunitACase");
		s.add("JunitADAM");
		s.add("JunitADATA Technology");
		s.add("JunitADG Source");
		s.add("JunitAERIAL7");
		s.add("JunitAES");
		s.add("JunitAF Lighting");
		s.add("JunitAFG Fitness");
		s.add("JunitAGENT 18");
		s.add("JunitAGPtek");
		s.add("JunitAIAIAI");
		s.add("JunitAIMO");
		s.add("JunitAIRBAC");
		s.add("JunitAIRFLOW COLLECTIBLES");
		s.add("JunitAKG");
		s.add("JunitALPS");
		s.add("JunitALPS Mountaineering");
		s.add("JunitALS");
		s.add("JunitALS Industries");
		s.add("JunitAMAZON FULFILLMENT SERVICES");
		s.add("JunitAMC Optics");
		s.add("JunitAMCO Houseworks");
		s.add("JunitAMD");
		s.add("JunitAMEP");
		s.add("JunitAMP Energy");
		s.add("JunitAMT");
		s.add("JunitAOC");
		s.add("JunitAOpen");
		s.add("JunitAPC");
		s.add("JunitAPPLE COMP. INC.");
		s.add("JunitAPPLE COMPUTER INC");
		s.add("JunitAPPLE COMPUTER INC.");
		s.add("JunitARKON");
		s.add("JunitARY");
		s.add("JunitASTRO Gaming");
		s.add("JunitASUS");
		s.add("JunitASUS COMPUTER INTL");
		s.add("JunitAT&T");
		s.add("JunitAT&T GoPhone");
		s.add("JunitAT&T MOBILITY.");
		s.add("JunitATN");
		s.add("JunitATON");
		s.add("JunitATTO");
		s.add("JunitAUDIO AMERICA");
		s.add("JunitAVF");
		s.add("JunitAVF Nexus");
		s.add("JunitAVF Unimax");
		s.add("JunitAVOCENT");
		s.add("JunitAVUE");
		s.add("JunitAVer");
		s.add("JunitAVerMedia");
		s.add("JunitAViiQ");
		s.add("JunitAWS");
		s.add("JunitAZ Patio Heaters");
		s.add("JunitAZEND GROUP CORP");
		s.add("JunitAZT POS");
		s.add("JunitAastra");
		s.add("JunitAble Planet");
		s.add("JunitAbleton");
		s.add("JunitAccell");
		s.add("JunitAccess Lighting");
		s.add("JunitAccessory Export");
		s.add("JunitAccessory Export LLC");
		s.add("JunitAccessory Genie");
		s.add("JunitAccessory Power");
		s.add("JunitAcco");
		s.add("JunitAccoutrements");
		s.add("JunitAccu Cable");
		s.add("JunitAccuScreens");
		s.add("JunitAccuTorq");
		s.add("JunitAccudart");
		s.add("JunitAccusplit");
		s.add("JunitAce Bayou");
		s.add("JunitAce Bayou Corporation");
		s.add("JunitAcer");
		s.add("JunitAcme Made");
		s.add("JunitAcme United");
		s.add("JunitAcomData");
		s.add("JunitAcoustic Audio");
		s.add("JunitAcoustic Research");
		s.add("JunitAction Sport Drives");
		s.add("JunitAction Sport Drives Powered by SanDisk");
		s.add("JunitActiontec");
		s.add("JunitActivision");
		s.add("JunitAdaptec");
		s.add("JunitAdata");
		s.add("JunitAddOn - Memory Upgrades");
		s.add("JunitAddOn - Network Upgrades");
		s.add("JunitAddlogix");
		s.add("JunitAddon - Network Upgrades");
		s.add("JunitAddonics");
		s.add("JunitAdesso");
		s.add("JunitAdobe");
		s.add("JunitAdonit");
		s.add("JunitAdorama");
		s.add("JunitAdrenaline");
		s.add("JunitAdtran");
		s.add("JunitAdvantus");
		s.add("JunitAdventure Products");
		s.add("JunitAerielle");
		s.add("JunitAeromat");
		s.add("JunitAeromax");
		s.add("JunitAffinity");
		s.add("JunitAffresh");
		s.add("JunitAfterShokz");
		s.add("JunitAgent18");
		s.add("JunitAgfaPhoto");
		s.add("JunitAgptek");
		s.add("JunitAi");
		s.add("JunitAiptek");
		s.add("JunitAir King");
		s.add("JunitAir Swimmers");
		s.add("JunitAirflow Collectibles");
		s.add("JunitAirhead");
		s.add("JunitAirpura");
		s.add("JunitAkai");
		s.add("JunitAkai Professional");
		s.add("JunitAl Cass");
		s.add("JunitAlaska");
		s.add("JunitAlba");
		s.add("JunitAlcatel");
		s.add("JunitAleken Games");
		s.add("JunitAlera");
		s.add("JunitAleratec");
		s.add("JunitAlesis");
		s.add("JunitAlex");
		s.add("JunitAlfred");
		s.add("JunitAlico");
		s.add("JunitAlienware");
		s.add("JunitAll Power America");
		s.add("JunitAll The King's Games");
		s.add("JunitAll Things Equal");
		s.add("JunitAllant");
		s.add("JunitAllen");
		s.add("JunitAllen & Heath");
		s.add("JunitAllied Telesis");
		s.add("JunitAllsop");
		s.add("JunitAllure Eyewear");
		s.add("JunitAlma's Designs");
		s.add("JunitAlpen");
		s.add("JunitAlpen Outdoor");
		s.add("JunitAlpine");
		s.add("JunitAlpine Innovations");
		s.add("JunitAltaz");
		s.add("JunitAltec Lansing");
		s.add("JunitAltec Lansing LLC");
		s.add("JunitAltego");
		s.add("JunitAltra");
		s.add("JunitAluma Wallet");
		s.add("JunitAluratek");
		s.add("JunitAlvin");
		s.add("JunitAmana");
		s.add("JunitAmazon");
		s.add("JunitAmbia");
		s.add("JunitAmbir");
		s.add("JunitAmer");
		s.add("JunitAmeriBag");
		s.add("JunitAmerican Audio");
		s.add("JunitAmerican Comfort");
		s.add("JunitAmerican Covers");
		s.add("JunitAmerican DJ");
		s.add("JunitAmerican Flyer");
		s.add("JunitAmerican Heritage");
		s.add("JunitAmerican Home");
		s.add("JunitAmerican Originals");
		s.add("JunitAmerican Plastic Toys");
		s.add("JunitAmerican Power Conversion");
		s.add("JunitAmerican Recorder");
		s.add("JunitAmerican Technology");
		s.add("JunitAmerican Tourister");
		s.add("JunitAmerican Trading House");
		s.add("JunitAmerican Traveler");
		s.add("JunitAmerican Weigh Scales");
		s.add("JunitAmerihome");
		s.add("JunitAmeriphone");
		s.add("JunitAmeristep");
		s.add("JunitAmeriwood");
		s.add("JunitAmes True Temper");
		s.add("JunitAmloid");
		s.add("JunitAmped Wireless");
		s.add("JunitAmpeg");
		s.add("JunitAmperGen");
		s.add("JunitAmpliVox");
		s.add("JunitAmpliVox Sound Systems");
		s.add("JunitAmzer");
		s.add("JunitAnchor Bay");
		s.add("JunitAndis");
		s.add("JunitAndrea");
		s.add("JunitAngel");
		s.add("JunitAngry Birds");
		s.add("JunitAnimoes");
		s.add("JunitAnji");
		s.add("JunitAnnex");
		s.add("JunitAnolon");
		s.add("JunitAnomia Press");
		s.add("JunitAnsmann");
		s.add("JunitAnt Farm");
		s.add("JunitAntares");
		s.add("JunitAntec");
		s.add("JunitAntennas Direct");
		s.add("JunitAntennaworks");
		s.add("JunitAntler");
		s.add("JunitAnvid");
		s.add("JunitApe Case");
		s.add("JunitApen");
		s.add("JunitApex");
		s.add("JunitApollo");
		s.add("JunitAppGear");
		s.add("JunitAppfinity");
		s.add("JunitApple");
		s.add("JunitApplecreek");
		s.add("JunitApple®");
		s.add("JunitApplica");
		s.add("JunitApricorn");
		s.add("JunitAquaglide");
		s.add("JunitAquapac");
		s.add("JunitAquarian");
		s.add("JunitAquarius");
		s.add("JunitArachnid");
		s.add("JunitAraneus");
		s.add("JunitArchiTech");
		s.add("JunitArchitec");
		s.add("JunitArchitech");
		s.add("JunitArchos");
		s.add("JunitArclyte");
		s.add("JunitArctic");
		s.add("JunitArctic Cooling");
		s.add("JunitArctic Silver");
		s.add("JunitArctic Start");
		s.add("JunitArdent");
		s.add("JunitAreYouGame");
		s.add("JunitAreca");
		s.add("JunitAristoplay");
		s.add("JunitArkon");
		s.add("JunitArm & Hammer");
		s.add("JunitArmaSport");
		s.add("JunitArmen Living");
		s.add("JunitArmitron");
		s.add("JunitArmor All");
		s.add("JunitArmpocket");
		s.add("JunitArmstrong Tools");
		s.add("JunitArnold");
		s.add("JunitArnova");
		s.add("JunitAroma");
		s.add("JunitAround the Table games");
		s.add("JunitArrow");
		s.add("JunitArt Vinyl");
		s.add("JunitArtDio");
		s.add("JunitArtistic");
		s.add("JunitAs Seen On TV");
		s.add("JunitAs Seen on TV");
		s.add("JunitAsante");
		s.add("JunitAshley");
		s.add("JunitAshlin");
		s.add("JunitAsia Direct");
		s.add("JunitAssociated Electrics");
		s.add("JunitAstatic");
		s.add("JunitAstro");
		s.add("JunitAstro Gaming");
		s.add("JunitAsus");
		s.add("JunitAt Home with the O");
		s.add("JunitAtari");
		s.add("JunitAtdec");
		s.add("JunitAtek");
		s.add("JunitAten");
		s.add("JunitAten Technology");
		s.add("JunitAthalon");
		s.add("JunitAthena");
		s.add("JunitAthenatech");
		s.add("JunitAtlantic");
		s.add("JunitAtlantic Furniture");
		s.add("JunitAtlantic Technology");
		s.add("JunitAtlantis");
		s.add("JunitAtlona");
		s.add("JunitAtlus");
		s.add("JunitAtomic9");
		s.add("JunitAtrend");
		s.add("JunitAu'some");
		s.add("JunitAudio America");
		s.add("JunitAudio Spectrum");
		s.add("JunitAudio Technica");
		s.add("JunitAudio Unlimited");
		s.add("JunitAudio-Technica");
		s.add("JunitAudioQuest");
		s.add("JunitAudioSource");
		s.add("JunitAudiobahn");
		s.add("JunitAudioengine");
		s.add("JunitAudiopipe");
		s.add("JunitAudiovox");
		s.add("JunitAudix");
		s.add("JunitAudyssey");
		s.add("JunitAuralex");
		s.add("JunitAustin");
		s.add("JunitAustin Air");
		s.add("JunitAutoExec");
		s.add("JunitAutoPage");
		s.add("JunitAutotek");
		s.add("JunitAvalon Hill");
		s.add("JunitAvant");
		s.add("JunitAvanti");
		s.add("JunitAvari");
		s.add("JunitAve Six");
		s.add("JunitAvenue Six");
		s.add("JunitAvery");
		s.add("JunitAvid");
		s.add("JunitAvista");
		s.add("JunitAvital");
		s.add("JunitAvocent");
		s.add("JunitAvon");
		s.add("JunitAvue");
		s.add("JunitAxiom");
		s.add("JunitAxion");
		s.add("JunitAxis");
		s.add("JunitAxxess");
		s.add("JunitAzden");
		s.add("JunitAzend");
		s.add("JunitAziO");
		s.add("JunitAzpen");
		s.add("JunitAztec");
		s.add("JunitAztech");
		s.add("JunitB&B");
		s.add("JunitB&F System");
		s.add("JunitB&W");
		s.add("JunitB+W");
		s.add("JunitB-Grip");
		s.add("JunitB.C. Rich");
		s.add("JunitB.E.S");
		s.add("JunitBACtrack");
		s.add("JunitBAGGO");
		s.add("JunitBBE Sound");
		s.add("JunitBD&A");
		s.add("JunitBDI");
		s.add("JunitBELKIN INC");
		s.add("JunitBH FITNESS");
		s.add("JunitBIC");
		s.add("JunitBIC America");
		s.add("JunitBIC Corporation");
		s.add("JunitBIOS");
		s.add("JunitBISSELL");
		s.add("JunitBITS");
		s.add("JunitBNF");
		s.add("JunitBOSCH");
		s.add("JunitBOSE");
		s.add("JunitBOSS");
		s.add("JunitBOSS Audio Systems");
		s.add("JunitBOXIS autoshred");
		s.add("JunitBPM");
		s.add("JunitBPong");
		s.add("JunitBRACKETRON CONSIGN 011");
		s.add("JunitBRAVEN");
		s.add("JunitBRIGHTSTAR US");
		s.add("JunitBRK");
		s.add("JunitBSN Sports");
		s.add("JunitBTI");
		s.add("JunitBUNN");
		s.add("JunitBUY.COM");
		s.add("JunitBaByliss");
		s.add("JunitBabalu");
		s.add("JunitBabyPing");
		s.add("JunitBabyliss");
		s.add("JunitBabylissPRO");
		s.add("JunitBaccus Global");
		s.add("JunitBachmann");
		s.add("JunitBachmann Trains");
		s.add("JunitBack");
		s.add("JunitBack To Basics");
		s.add("JunitBack to Basics");
		s.add("JunitBadger Basket");
		s.add("JunitBafo");
		s.add("JunitBall & Chain");
		s.add("JunitBallistic");
		s.add("JunitBalt");
		s.add("JunitBananagrams");
		s.add("JunitBandai");
		s.add("JunitBanpresto");
		s.add("JunitBaracoda");
		s.add("JunitBaratza");
		s.add("JunitBarbie");
		s.add("JunitBarbour");
		s.add("JunitBarker Creek");
		s.add("JunitBarnel");
		s.add("JunitBarnes & Noble");
		s.add("JunitBarnie's");
		s.add("JunitBaron");
		s.add("JunitBarska");
		s.add("JunitBaseline");
		s.add("JunitBasic Fun");
		s.add("JunitBassInferno");
		s.add("JunitBasu");
		s.add("JunitBasyx by HON");
		s.add("JunitBattat");
		s.add("JunitBattery Biz");
		s.add("JunitBattery Genie");
		s.add("JunitBattery-Biz");
		s.add("JunitBausch & Lomb");
		s.add("JunitBaxton Studios");
		s.add("JunitBayco");
		s.add("JunitBayou Classic");
		s.add("JunitBayou Fitness");
		s.add("JunitBazooka");
		s.add("JunitBe A HeadCase");
		s.add("JunitBe Amazing!");
		s.add("JunitBe Good Company");
		s.add("JunitBePuzzled");
		s.add("JunitBeacon");
		s.add("JunitBeamz");
		s.add("JunitBear Archery");
		s.add("JunitBeast Kords");
		s.add("JunitBeat  Kangz");
		s.add("JunitBeats By Dr. Dre");
		s.add("JunitBeats by Dr. Dre");
		s.add("JunitBed Head");
		s.add("JunitBeeline Creative");
		s.add("JunitBehringer");
		s.add("JunitBelkin");
		s.add("JunitBell & Howell");
		s.add("JunitBell and Howell");
		s.add("JunitBell'O");
		s.add("JunitBella Cucina");
		s.add("JunitBella Professional");
		s.add("JunitBelson");
		s.add("JunitBeltronics");
		s.add("JunitBenQ");
		s.add("JunitBenetton");
		s.add("JunitBenzara");
		s.add("JunitBepuzzled");
		s.add("JunitBerard");
		s.add("JunitBerghoff");
		s.add("JunitBernards");
		s.add("JunitBerndes");
		s.add("JunitBest  Buy GC");
		s.add("JunitBest Buy");
		s.add("JunitBest Buy GC");
		s.add("JunitBest Fitness");
		s.add("JunitBest Green");
		s.add("JunitBest-Lock");
		s.add("JunitBestAir");
		s.add("JunitBestBuy GC");
		s.add("JunitBestBuyGC");
		s.add("JunitBethany Housewares");
		s.add("JunitBetseyville");
		s.add("JunitBetter Chef");
		s.add("JunitBeurer");
		s.add("JunitBeverly Hills County Club");
		s.add("JunitBiGR Audio");
		s.add("JunitBialetti");
		s.add("JunitBif Bang Pow!");
		s.add("JunitBig Ben");
		s.add("JunitBig Fish Games");
		s.add("JunitBiggest Looser");
		s.add("JunitBikini Touch");
		s.add("JunitBilly Bob");
		s.add("JunitBinatone");
		s.add("JunitBionaire");
		s.add("JunitBiostar");
		s.add("JunitBioworld");
		s.add("JunitBissell");
		s.add("JunitBixolon");
		s.add("JunitBlack & Decker");
		s.add("JunitBlackBerry");
		s.add("JunitBlackHawk Labs");
		s.add("JunitBlackRapid");
		s.add("JunitBlackberry");
		s.add("JunitBlackstar");
		s.add("JunitBlade");
		s.add("JunitBladez Fitness");
		s.add("JunitBlender");
		s.add("JunitBlendtec");
		s.add("JunitBlizzard Entertainment");
		s.add("JunitBloomfield");
		s.add("JunitBlu");
		s.add("JunitBlu-Link");
		s.add("JunitBlue Crane");
		s.add("JunitBlue Crane Digital");
		s.add("JunitBlue Hat Toy Company");
		s.add("JunitBlue Juice");
		s.add("JunitBlue Microphones");
		s.add("JunitBlue Opal");
		s.add("JunitBlue Orange");
		s.add("JunitBlue Orange Games");
		s.add("JunitBlue Parrot");
		s.add("JunitBlue Rhino");
		s.add("JunitBlue Ridge");
		s.add("JunitBlue Sea");
		s.add("JunitBlue Trek");
		s.add("JunitBlueAnt");
		s.add("JunitBlueMax");
		s.add("JunitBlueair");
		s.add("JunitBluefox Extreme");
		s.add("JunitBluelounge");
		s.add("JunitBluewater");
		s.add("JunitBobble");
		s.add("JunitBoblbee");
		s.add("JunitBobster");
		s.add("JunitBodhi");
		s.add("JunitBodum");
		s.add("JunitBody Champ");
		s.add("JunitBody Flex");
		s.add("JunitBody Glide");
		s.add("JunitBody Glove");
		s.add("JunitBody Power");
		s.add("JunitBody Rider");
		s.add("JunitBody Rower");
		s.add("JunitBody Solid");
		s.add("JunitBody-Solid");
		s.add("JunitBodyGuardz");
		s.add("JunitBodyMedia");
		s.add("JunitBodyTel Scales Solutions");
		s.add("JunitBoelter");
		s.add("JunitBogen");
		s.add("JunitBoise");
		s.add("JunitBojeux");
		s.add("JunitBonJour");
		s.add("JunitBond");
		s.add("JunitBond Street");
		s.add("JunitBone");
		s.add("JunitBone Collection");
		s.add("JunitBongoTies");
		s.add("JunitBookEndz");
		s.add("JunitBoomBotix");
		s.add("JunitBoomChair");
		s.add("JunitBoon");
		s.add("JunitBooq");
		s.add("JunitBoost Mobile");
		s.add("JunitBoraam");
		s.add("JunitBorner");
		s.add("JunitBosch");
		s.add("JunitBosch Power Tools");
		s.add("JunitBose");
		s.add("JunitBose®");
		s.add("JunitBoss");
		s.add("JunitBoss Audio-Car Audio/video");
		s.add("JunitBoss Marine");
		s.add("JunitBostitch");
		s.add("JunitBoston Acoustics");
		s.add("JunitBoston Harbor");
		s.add("JunitBounty Hunter");
		s.add("JunitBower");
		s.add("JunitBowers & Wilkins");
		s.add("JunitBowers and Wilkins");
		s.add("JunitBowflex");
		s.add("JunitBoxis");
		s.add("JunitBoyo");
		s.add("JunitBracketron");
		s.add("JunitBradley Smoker");
		s.add("JunitBradyGames");
		s.add("JunitBrainboxes");
		s.add("JunitBrainy Toys");
		s.add("JunitBrand X");
		s.add("JunitBrands Unlimited");
		s.add("JunitBraun");
		s.add("JunitBraven");
		s.add("JunitBravo Sports");
		s.add("JunitBravoview");
		s.add("JunitBreadman");
		s.add("JunitBrenthaven");
		s.add("JunitBrentwood");
		s.add("JunitBretford");
		s.add("JunitBreville");
		s.add("JunitBreyer");
		s.add("JunitBriarPatch");
		s.add("JunitBriarpatch");
		s.add("JunitBright Light Pillow");
		s.add("JunitBrightstar");
		s.add("JunitBrinkmann");
		s.add("JunitBrinno");
		s.add("JunitBrno");
		s.add("JunitBroan");
		s.add("JunitBronica");
		s.add("JunitBrother");
		s.add("JunitBrowning");
		s.add("JunitBruder");
		s.add("JunitBrunton");
		s.add("JunitBrush Buddies");
		s.add("JunitBucephalus");
		s.add("JunitBuckmasters");
		s.add("JunitBuckyballs");
		s.add("JunitBuddy");
		s.add("JunitBudweiser");
		s.add("JunitBuffalo");
		s.add("JunitBuffalo Games");
		s.add("JunitBuffalo Technology");
		s.add("JunitBuffalo Tools");
		s.add("JunitBuffet Enhancements");
		s.add("JunitBuhl Industries");
		s.add("JunitBuilt NY");
		s.add("JunitBull");
		s.add("JunitBunn");
		s.add("JunitBunn-O-Matic Corp.");
		s.add("JunitBury");
		s.add("JunitBush");
		s.add("JunitBush Signature");
		s.add("JunitBushnell");
		s.add("JunitBuslink");
		s.add("JunitButler");
		s.add("JunitButler Creek");
		s.add("JunitButterball");
		s.add("JunitButterfly");
		s.add("JunitBuxton");
		s.add("JunitBytecc");
		s.add("JunitBytech");
		s.add("JunitC & A Scientific");
		s.add("JunitC and N Reproductions");
		s.add("JunitC&N Reproductions");
		s.add("JunitC-line");
		s.add("JunitC2G");
		s.add("JunitCAA");
		s.add("JunitCAD");
		s.add("JunitCAD Audio");
		s.add("JunitCANON");
		s.add("JunitCANON USA");
		s.add("JunitCAP");
		s.add("JunitCASE LOGIC");
		s.add("JunitCCT");
		s.add("JunitCDI");
		s.add("JunitCE Labs");
		s.add("JunitCED, INC");
		s.add("JunitCEM Global");
		s.add("JunitCET Domain");
		s.add("JunitCH Products");
		s.add("JunitCHH");
		s.add("JunitCHI Air");
		s.add("JunitCHI Bling");
		s.add("JunitCHI Smart");
		s.add("JunitCIA");
		s.add("JunitCINEMANOW");
		s.add("JunitCLARO");
		s.add("JunitCLC");
		s.add("JunitCM Storm");
		s.add("JunitCMG");
		s.add("JunitCMS");
		s.add("JunitCMS Products");
		s.add("JunitCNet");
		s.add("JunitCP TECH");
		s.add("JunitCRANE USA");
		s.add("JunitCRU");
		s.add("JunitCSDC");
		s.add("JunitCTA");
		s.add("JunitCTG");
		s.add("JunitCTL");
		s.add("JunitCTL Corp");
		s.add("JunitCableWholesale");
		s.add("JunitCables To Go");
		s.add("JunitCables Unlimited");
		s.add("JunitCablesys");
		s.add("JunitCadaco");
		s.add("JunitCadet");
		s.add("JunitCakewalk");
		s.add("JunitCalPak");
		s.add("JunitCalculated Industries");
		s.add("JunitCalebou");
		s.add("JunitCalibur11");
		s.add("JunitCalico Critter");
		s.add("JunitCalifone");
		s.add("JunitCalifornia Costume");
		s.add("JunitCall of Duty: Black Ops II");
		s.add("JunitCallaway");
		s.add("JunitCalphalon");
		s.add("JunitCalrad Electronics");
		s.add("JunitCam Caddie");
		s.add("JunitCambor Games");
		s.add("JunitCamco");
		s.add("JunitCamelBak");
		s.add("JunitCamera Armor");
		s.add("JunitCamp Chef");
		s.add("JunitCan-C");
		s.add("JunitCandice Olson");
		s.add("JunitCando");
		s.add("JunitCando AccuForce");
		s.add("JunitCanon");
		s.add("JunitCanson");
		s.add("JunitCapital Brands");
		s.add("JunitCapresso");
		s.add("JunitCar And Driver");
		s.add("JunitCarbon Audio");
		s.add("JunitCardinal");
		s.add("JunitCardscan");
		s.add("JunitCaribee");
		s.add("JunitCarlon");
		s.add("JunitCarmanah");
		s.add("JunitCarolina");
		s.add("JunitCarolina Pad");
		s.add("JunitCarpet Pro");
		s.add("JunitCarrera");
		s.add("JunitCarrom");
		s.add("JunitCarson");
		s.add("JunitCarson-Dellosa");
		s.add("JunitCasauri");
		s.add("JunitCase Logic");
		s.add("JunitCase-Mate");
		s.add("JunitCaseCrown");
		s.add("JunitCasemaster");
		s.add("JunitCaseworks");
		s.add("JunitCasio");
		s.add("JunitCasioherry");
		s.add("JunitCasiooby");
		s.add("JunitCasket");
		s.add("JunitCatskill");
		s.add("JunitCavalry");
		s.add("JunitCavalry Storage");
		s.add("JunitCeaco");
		s.add("JunitCelestion");
		s.add("JunitCelestron");
		s.add("JunitCellbatt");
		s.add("JunitCellet");
		s.add("JunitCelltronix");
		s.add("JunitCellular Innovations");
		s.add("JunitCelluon");
		s.add("JunitCem Global");
		s.add("JunitCenter Stage Bracket");
		s.add("JunitCenton");
		s.add("JunitCentral Tools");
		s.add("JunitCentury");
		s.add("JunitCenturyLink");
		s.add("JunitCerevo");
		s.add("JunitCertance");
		s.add("JunitCerwin Vega");
		s.add("JunitCerwin-Vega!");
		s.add("JunitChamberlain");
		s.add("JunitChameleon Gear");
		s.add("JunitChampion");
		s.add("JunitChampion Treasures");
		s.add("JunitChaney");
		s.add("JunitChannel Craft");
		s.add("JunitChannel Master");
		s.add("JunitChannel Vision");
		s.add("JunitChannelPlus");
		s.add("JunitChar-Broil");
		s.add("JunitChar-Griller");
		s.add("JunitCharbroil");
		s.add("JunitCharcoal Companion");
		s.add("JunitCharming Pet");
		s.add("JunitCharter");
		s.add("JunitChatman");
		s.add("JunitChauvet Lighting");
		s.add("JunitCheck Point");
		s.add("JunitCheck-It");
		s.add("JunitChef Buddy");
		s.add("JunitChef Sleeve");
		s.add("JunitChef Tony");
		s.add("JunitChef's Choice");
		s.add("JunitChef's Kitchen");
		s.add("JunitChef's Secret");
		s.add("JunitChef'sChoice");
		s.add("JunitChefmaster");
		s.add("JunitChefs Basics");
		s.add("JunitChefsChoice");
		s.add("JunitChenbro");
		s.add("JunitChenille Kraft");
		s.add("JunitChenilleKraft");
		s.add("JunitCherry");
		s.add("JunitCherry  Healthcare");
		s.add("JunitCherry Lane Music");
		s.add("JunitChess on DVD");
		s.add("JunitChessBase");
		s.add("JunitChessCentral");
		s.add("JunitChester Creek");
		s.add("JunitChicago Cutlery");
		s.add("JunitChicago Gaming Company");
		s.add("JunitChicago Metallic");
		s.add("JunitChief");
		s.add("JunitChief Manufacturing");
		s.add("JunitChill Pill");
		s.add("JunitChill Pill Audio");
		s.add("JunitChinook");
		s.add("JunitChip PC");
		s.add("JunitChoiix");
		s.add("JunitChroma Cutlery");
		s.add("JunitCimo");
		s.add("JunitCinema Secrets");
		s.add("JunitCinema of Fear");
		s.add("JunitCinemaNow");
		s.add("JunitCirago");
		s.add("JunitCirc");
		s.add("JunitCirculon");
		s.add("JunitCisco");
		s.add("JunitCisco Linksys");
		s.add("JunitCitiblocs");
		s.add("JunitCitizen");
		s.add("JunitClaessens' Kids");
		s.add("JunitClaire Chase");
		s.add("JunitClaireChase");
		s.add("JunitClarion");
		s.add("JunitClarity");
		s.add("JunitClarity AlertMaster");
		s.add("JunitClarity Professional");
		s.add("JunitClarityOne");
		s.add("JunitClaro");
		s.add("JunitClassic Accessories");
		s.add("JunitClassroom Complete Press");
		s.add("JunitClava");
		s.add("JunitCleanDr");
		s.add("JunitClearLinks");
		s.add("JunitClearOne");
		s.add("JunitClearSounds");
		s.add("JunitClickfree");
		s.add("JunitClik Elite");
		s.add("JunitClingo");
		s.add("JunitClipper");
		s.add("JunitClipper Marine Instruments");
		s.add("JunitClorox");
		s.add("JunitCloud B");
		s.add("JunitClover");
		s.add("JunitClover Technologies");
		s.add("JunitClue");
		s.add("JunitCmple");
		s.add("JunitCnet");
		s.add("JunitCoaster");
		s.add("JunitCobble Hill");
		s.add("JunitCobble Hill Puzzle Company");
		s.add("JunitCobra");
		s.add("JunitCobra Digital");
		s.add("JunitCoby");
		s.add("JunitCoca-Cola");
		s.add("JunitCocoon");
		s.add("JunitCocoon Innovations");
		s.add("JunitCodi");
		s.add("JunitCodigo Cube");
		s.add("JunitCoffee People");
		s.add("JunitCoffee Pro");
		s.add("JunitCoffeemaker");
		s.add("JunitCoghlan's");
		s.add("JunitCokem International");
		s.add("JunitCokin");
		s.add("JunitColeman");
		s.add("JunitColeman Cable");
		s.add("JunitColorforms");
		s.add("JunitColumbia");
		s.add("JunitComcast");
		s.add("JunitComet");
		s.add("JunitComfort Zone");
		s.add("JunitComfort-Aire");
		s.add("JunitComic Images");
		s.add("JunitCommand");
		s.add("JunitCommonwealth");
		s.add("JunitCompanion Group");
		s.add("JunitCompaq");
		s.add("JunitComply");
		s.add("JunitComprehensive");
		s.add("JunitComprehensive Video");
		s.add("JunitCompuStar");
		s.add("JunitCompucessory");
		s.add("JunitComputer Apparel");
		s.add("JunitComtrol");
		s.add("JunitConair");
		s.add("JunitConairPRO");
		s.add("JunitConcept");
		s.add("JunitConcept Green");
		s.add("JunitConcept One");
		s.add("JunitConnecticut Electric");
		s.add("JunitConnectland");
		s.add("JunitConnectpro");
		s.add("JunitContigo");
		s.add("JunitContinental Electric");
		s.add("JunitContinental Platinum");
		s.add("JunitContinuum Games");
		s.add("JunitContour");
		s.add("JunitConvenience Concepts");
		s.add("JunitCool Components");
		s.add("JunitCooler Master");
		s.add("JunitCooler Master Usa");
		s.add("JunitCoolerMaster");
		s.add("JunitCoolmax");
		s.add("JunitCooper");
		s.add("JunitCooper Classics");
		s.add("JunitCooper Cooler");
		s.add("JunitCooper Tools");
		s.add("JunitCooper Wheelock");
		s.add("JunitCooper Wiring");
		s.add("JunitCopag");
		s.add("JunitCopernicus");
		s.add("JunitCoral Coast");
		s.add("JunitCordoba");
		s.add("JunitCore Bamboo");
		s.add("JunitCorel");
		s.add("JunitCorningWare");
		s.add("JunitCorolle");
		s.add("JunitCoronado");
		s.add("JunitCorsair");
		s.add("JunitCortelco");
		s.add("JunitCostume Evolution");
		s.add("JunitCotton Candy Cutesies");
		s.add("JunitCotytech");
		s.add("JunitCoustic");
		s.add("JunitCoverSports");
		s.add("JunitCoveroo");
		s.add("JunitCox");
		s.add("JunitCoyote Point");
		s.add("JunitCradlePoint");
		s.add("JunitCramer");
		s.add("JunitCrane");
		s.add("JunitCranium");
		s.add("JunitCrayola");
		s.add("JunitCrazyOnDigital");
		s.add("JunitCreations By You");
		s.add("JunitCreative");
		s.add("JunitCreative Education");
		s.add("JunitCreative Essentials");
		s.add("JunitCreative Labs");
		s.add("JunitCreative Motion");
		s.add("JunitCreative Teaching Press");
		s.add("JunitCrescent");
		s.add("JunitCrescent Moon");
		s.add("JunitCrest Audio");
		s.add("JunitCrimestopper");
		s.add("JunitCrock-Pot");
		s.add("JunitCrock-pot");
		s.add("JunitCrooked Horn");
		s.add("JunitCrosley");
		s.add("JunitCrosley Furniture");
		s.add("JunitCrown");
		s.add("JunitCrown Edition");
		s.add("JunitCrucial");
		s.add("JunitCrucial Memory");
		s.add("JunitCrucial Technology");
		s.add("JunitCrumpler");
		s.add("JunitCrunch");
		s.add("JunitCryptozoic Entertainment");
		s.add("JunitCrystal Optics");
		s.add("JunitCrystorama");
		s.add("JunitCuckoo Electronics");
		s.add("JunitCuddleUppets");
		s.add("JunitCuisinart");
		s.add("JunitCuisinox");
		s.add("JunitCulinair");
		s.add("JunitCulligan");
		s.add("JunitCurious Bonz");
		s.add("JunitCurtis-Young");
		s.add("JunitCyber Acoustics");
		s.add("JunitCyber Clean");
		s.add("JunitCyber Snipa");
		s.add("JunitCyberPower");
		s.add("JunitCyberPowerPC");
		s.add("JunitCyberpower");
		s.add("JunitCyborg");
		s.add("JunitCyclades");
		s.add("JunitCyclops");
		s.add("JunitCygnett");
		s.add("JunitCypher Entertainment");
		s.add("JunitD&H Distributing");
		s.add("JunitD'Addario");
		s.add("JunitD'Andrea");
		s.add("JunitD-Link");
		s.add("JunitD2");
		s.add("JunitDATA LOCKER");
		s.add("JunitDB Drive");
		s.add("JunitDB Link");
		s.add("JunitDBL Distributing, Inc");
		s.add("JunitDBX");
		s.add("JunitDBZ Guitars");
		s.add("JunitDC Comics");
		s.add("JunitDC Universe");
		s.add("JunitDCI");
		s.add("JunitDCT");
		s.add("JunitDELL, INC");
		s.add("JunitDENON");
		s.add("JunitDGL Group");
		s.add("JunitDIAMOND");
		s.add("JunitDICE");
		s.add("JunitDICOTA");
		s.add("JunitDIRECTED ELECTRONICS");
		s.add("JunitDIRECTED ELECTRONICS INC. 011");
		s.add("JunitDIRECTV");
		s.add("JunitDISH Network");
		s.add("JunitDITEK");
		s.add("JunitDJ-Tech");
		s.add("JunitDKN");
		s.add("JunitDLC");
		s.add("JunitDLO");
		s.add("JunitDMI");
		s.add("JunitDMI Sports");
		s.add("JunitDMT");
		s.add("JunitDPI");
		s.add("JunitDPI, INC");
		s.add("JunitDR");
		s.add("JunitDU-BRO");
		s.add("JunitDW");
		s.add("JunitDYMO");
		s.add("JunitDYSE");
		s.add("JunitDa-Lite");
		s.add("JunitDaVinci");
		s.add("JunitDaddy-O");
		s.add("JunitDaewoo");
		s.add("JunitDaisy Rock");
		s.add("JunitDakota Alert");
		s.add("JunitDanby");
		s.add("JunitDanby Designer");
		s.add("JunitDane-Elec");
		s.add("JunitDanelectro");
		s.add("JunitDantona");
		s.add("JunitDark Horse");
		s.add("JunitDaron");
		s.add("JunitDart World");
		s.add("JunitDas Keyboard");
		s.add("JunitDascom");
		s.add("JunitDataCal");
		s.add("JunitDataCal Enterprises");
		s.add("JunitDataLocker");
		s.add("JunitDataStor");
		s.add("JunitDataStream");
		s.add("JunitDatago");
		s.add("JunitDataproducts");
		s.add("JunitDatexx");
		s.add("JunitDavid King");
		s.add("JunitDavis & Sanford");
		s.add("JunitDavis Instruments");
		s.add("JunitDay-Timer");
		s.add("JunitDayMen");
		s.add("JunitDays of Wonder");
		s.add("JunitDbest");
		s.add("JunitDeLonghi");
		s.add("JunitDeLorme");
		s.add("JunitDeWalt");
		s.add("JunitDean");
		s.add("JunitDean Guitars");
		s.add("JunitDeco Breeze");
		s.add("JunitDecor");
		s.add("JunitDefinitive");
		s.add("JunitDefinitive Technology");
		s.add("JunitDeflect-o");
		s.add("JunitDelk");
		s.add("JunitDelkin");
		s.add("JunitDell");
		s.add("JunitDell-IMSourcing");
		s.add("JunitDelonghi");
		s.add("JunitDelphi");
		s.add("JunitDelsey");
		s.add("JunitDelta");
		s.add("JunitDelta|Porter-Cable");
		s.add("JunitDeluo");
		s.add("JunitDeluxGear");
		s.add("JunitDemeyere");
		s.add("JunitDenaq");
		s.add("JunitDenco");
		s.add("JunitDeni");
		s.add("JunitDenon");
		s.add("JunitDenon DJ");
		s.add("JunitDesign Toscano");
		s.add("JunitDesigner Sleeves");
		s.add("JunitDeskpets");
		s.add("JunitDevon IT");
		s.add("JunitDexim");
		s.add("JunitDexton");
		s.add("JunitDiCAPac");
		s.add("JunitDiVoga");
		s.add("JunitDiablotek");
		s.add("JunitDiamond");
		s.add("JunitDiamond Multimedia");
		s.add("JunitDiamond Select");
		s.add("JunitDice Electronics");
		s.add("JunitDicota");
		s.add("JunitDidax");
		s.add("JunitDiggin");
		s.add("JunitDigi");
		s.add("JunitDigiPower");
		s.add("JunitDigiStore");
		s.add("JunitDigiTech");
		s.add("JunitDigicom Digital");
		s.add("JunitDigifit");
		s.add("JunitDigipower");
		s.add("JunitDigital Antenna");
		s.add("JunitDigital Blue");
		s.add("JunitDigital Concept");
		s.add("JunitDigital Concepts");
		s.add("JunitDigital Innovations");
		s.add("JunitDigital Silence");
		s.add("JunitDigital Spectrum");
		s.add("JunitDigital Sun");
		s.add("JunitDigital Treasures");
		s.add("JunitDigitat");
		s.add("JunitDigiwave");
		s.add("JunitDimond Lighting");
		s.add("JunitDimplex");
		s.add("JunitDirected Elec-Alarms");
		s.add("JunitDirected Electronics");
		s.add("JunitDirections East");
		s.add("JunitDirt Devil");
		s.add("JunitDiscgear");
		s.add("JunitDiscover");
		s.add("JunitDiscovery Bay Games");
		s.add("JunitDiscovery Kids");
		s.add("JunitDisguise");
		s.add("JunitDisney");
		s.add("JunitDisney Interactive Studios");
		s.add("JunitDisney Pixar");
		s.add("JunitDisney Princess");
		s.add("JunitDisney/Pixar");
		s.add("JunitDistinctive");
		s.add("JunitDixie Seating Co");
		s.add("JunitDixon");
		s.add("JunitDoberman");
		s.add("JunitDoberman Security");
		s.add("JunitDolica");
		s.add("JunitDomke");
		s.add("JunitDonnieAnn Company");
		s.add("JunitDorcy");
		s.add("JunitDot Line");
		s.add("JunitDouble Power");
		s.add("JunitDouble-Take");
		s.add("JunitDoubleSight");
		s.add("JunitDoubleSight Displays");
		s.add("JunitDoubleStar");
		s.add("JunitDouglas");
		s.add("JunitDowdle Folk Art");
		s.add("JunitDr Heater");
		s.add("JunitDr. Koffer");
		s.add("JunitDr. Tech");
		s.add("JunitDrHotDeal");
		s.add("JunitDraper");
		s.add("JunitDream Cheeky");
		s.add("JunitDream Lites by Pillow Pets");
		s.add("JunitDreamGEAR");
		s.add("JunitDreamgear - Gaming");
		s.add("JunitDreamgirl");
		s.add("JunitDress Up America");
		s.add("JunitDrift");
		s.add("JunitDrift Innovation");
		s.add("JunitDrive Medical");
		s.add("JunitDriveway Games");
		s.add("JunitDrobo");
		s.add("JunitDrumFire");
		s.add("JunitDry Case");
		s.add("JunitDryCase");
		s.add("JunitDual");
		s.add("JunitDualit");
		s.add("JunitDucane");
		s.add("JunitDuck");
		s.add("JunitDumas");
		s.add("JunitDuncan Toys");
		s.add("JunitDuneCraft");
		s.add("JunitDunecraft");
		s.add("JunitDunlop");
		s.add("JunitDuo");
		s.add("JunitDuracell");
		s.add("JunitDuraflame");
		s.add("JunitDuroSonic");
		s.add("JunitDust-Off");
		s.add("JunitDymo");
		s.add("JunitDynamat");
		s.add("JunitDynamic Control");
		s.add("JunitDynamite");
		s.add("JunitDynatron");
		s.add("JunitDynavox");
		s.add("JunitDynex");
		s.add("JunitDynex Direct™");
		s.add("JunitDynex");
		s.add("JunitDyson");
		s.add("JunitE-Fun");
		s.add("JunitE-Series");
		s.add("JunitE-Stand");
		s.add("JunitE-flite");
		s.add("JunitE. Mishan");
		s.add("JunitEA Sports");
		s.add("JunitECO STYLE");
		s.add("JunitECO-heater");
		s.add("JunitECOXGEAR");
		s.add("JunitECR4KIDS");
		s.add("JunitECX");
		s.add("JunitEDGE");
		s.add("JunitEDU-Science");
		s.add("JunitEFX");
		s.add("JunitEFX Performance");
		s.add("JunitEKG");
		s.add("JunitEKHO");
		s.add("JunitELECTROLINE ELECTRONICS.");
		s.add("JunitELECTROLUX APPLIANCES");
		s.add("JunitELK Lighting");
		s.add("JunitELMO");
		s.add("JunitEMG");
		s.add("JunitEMTEC");
		s.add("JunitEP Memory");
		s.add("JunitERTL");
		s.add("JunitEVGA");
		s.add("JunitEWS");
		s.add("JunitEZ Dupe");
		s.add("JunitEZ Dupe-Computer");
		s.add("JunitEZPnP");
		s.add("JunitEagle Aspen");
		s.add("JunitEagle Optics");
		s.add("JunitEagle Tech Computers");
		s.add("JunitEagleCell");
		s.add("JunitEarBombz");
		s.add("JunitEarPollution");
		s.add("JunitEarloomz");
		s.add("JunitEarly Childhood Resources");
		s.add("JunitEarly Warning");
		s.add("JunitEarlyears");
		s.add("JunitEasyHeat");
		s.add("JunitEasyTouch");
		s.add("JunitEasystore");
		s.add("JunitEatSmart");
		s.add("JunitEaton");
		s.add("JunitEcko");
		s.add("JunitEcko Unltd.");
		s.add("JunitEcko unltd.");
		s.add("JunitEclipse");
		s.add("JunitEco-Que");
		s.add("JunitEcoQue");
		s.add("JunitEcogear");
		s.add("JunitEcolution");
		s.add("JunitEcosential");
		s.add("JunitEcosential by Smart Choice");
		s.add("JunitEctaco");
		s.add("JunitEd Hardy");
		s.add("JunitEddie Bauer");
		s.add("JunitEden");
		s.add("JunitEdgeCraft");
		s.add("JunitEdifier");
		s.add("JunitEdimax");
		s.add("JunitEduca");
		s.add("JunitEduca Borras");
		s.add("JunitEducational Insights");
		s.add("JunitEdushape");
		s.add("JunitEdutige");
		s.add("JunitEforcity");
		s.add("JunitEfun");
		s.add("JunitEidos");
		s.add("JunitEiko");
		s.add("JunitEizo");
		s.add("JunitEklind");
		s.add("JunitElchim");
		s.add("JunitElectric Friends");
		s.add("JunitElectro-Harmonix");
		s.add("JunitElectro-Voice");
		s.add("JunitElectroVoice");
		s.add("JunitElectrohome");
		s.add("JunitElectrolux");
		s.add("JunitElectrolux Home Care");
		s.add("JunitElectronic Arts");
		s.add("JunitElement");
		s.add("JunitElenco");
		s.add("JunitElexa");
		s.add("JunitElgato");
		s.add("JunitElgato Systems");
		s.add("JunitEliminator");
		s.add("JunitElinchrom");
		s.add("JunitElipse");
		s.add("JunitElite");
		s.add("JunitElite Image");
		s.add("JunitElite Screens");
		s.add("JunitElixir");
		s.add("JunitElkadart");
		s.add("JunitElmer's");
		s.add("JunitElmo");
		s.add("JunitElo");
		s.add("JunitElo- Accessories");
		s.add("JunitElsa");
		s.add("JunitEmatic");
		s.add("JunitEmedia Music");
		s.add("JunitEmer");
		s.add("JunitEmerald Home");
		s.add("JunitEmerge");
		s.add("JunitEmerson");
		s.add("JunitEminence");
		s.add("JunitEmjoi");
		s.add("JunitEmpire");
		s.add("JunitEmporium Leather");
		s.add("JunitEmson");
		s.add("JunitEmulex");
		s.add("JunitEnGenius");
		s.add("JunitEncore");
		s.add("JunitEncryptDisc");
		s.add("JunitEndLight");
		s.add("JunitEndless Games");
		s.add("JunitEndless Summer");
		s.add("JunitEndlessGames");
		s.add("JunitEndurance");
		s.add("JunitEndust");
		s.add("JunitEnergizer");
		s.add("JunitEnergy");
		s.add("JunitEnermax");
		s.add("JunitEnginuity");
		s.add("JunitEnhance");
		s.add("JunitEnitial Lab");
		s.add("JunitEnitial Labs");
		s.add("JunitEnterasys");
		s.add("JunitEnvizen Digital");
		s.add("JunitEpic");
		s.add("JunitEpicurean");
		s.add("JunitEpicureanist");
		s.add("JunitEpilady");
		s.add("JunitEpione");
		s.add("JunitEpoca");
		s.add("JunitEpson");
		s.add("JunitEquity by La Crosse");
		s.add("JunitErgoguys");
		s.add("JunitErgotech");
		s.add("JunitErgotron");
		s.add("JunitErnie Ball");
		s.add("JunitEscali");
		s.add("JunitEschenbach");
		s.add("JunitEscort");
		s.add("JunitEskuche");
		s.add("JunitEspressione");
		s.add("JunitEssick Air");
		s.add("JunitEsystor");
		s.add("JunitEtch A Sketch");
		s.add("JunitEthereal");
		s.add("JunitEton");
		s.add("JunitEtymotic");
		s.add("JunitEureka");
		s.add("JunitEuro Cuisine");
		s.add("JunitEuro Style");
		s.add("JunitEuro-Cuisine");
		s.add("JunitEuro-Pro");
		s.add("JunitEuroGraphics");
		s.add("JunitEurofase");
		s.add("JunitEurographics");
		s.add("JunitEuropean Gift");
		s.add("JunitEvans");
		s.add("JunitEverFocus");
		s.add("JunitEveready");
		s.add("JunitEverest");
		s.add("JunitEvergreen");
		s.add("JunitEverki");
		s.add("JunitEvolis");
		s.add("JunitEvoluent");
		s.add("JunitEvolution Robotics");
		s.add("JunitEvolving Toys");
		s.add("JunitEwa-Marine");
		s.add("JunitEx-Cell Kaiser");
		s.add("JunitExabyte");
		s.add("JunitExcalibur");
		s.add("JunitExcalibur Electronics");
		s.add("JunitExerpeutic");
		s.add("JunitExpedite");
		s.add("JunitExplore It!");
		s.add("JunitExpo");
		s.add("JunitExpoImaging");
		s.add("JunitExtreme Networks");
		s.add("JunitEye-Fi");
		s.add("JunitEzy Roller");
		s.add("JunitFAB Starpoint");
		s.add("JunitFAVI");
		s.add("JunitFEI");
		s.add("JunitFEIT");
		s.add("JunitFINIS");
		s.add("JunitFIRSTECH LLC.");
		s.add("JunitFRIGIDAIRE APPLIANCES");
		s.add("JunitFUJIFILM NORTH AMERICA");
		s.add("JunitFURUNO");
		s.add("JunitFUSION");
		s.add("JunitFUSION Electronics");
		s.add("JunitFabricas Selectas");
		s.add("JunitFabrique");
		s.add("JunitFabrique Innovations");
		s.add("JunitFaceVsion");
		s.add("JunitFacebook");
		s.add("JunitFactor");
		s.add("JunitFactory Entertainment");
		s.add("JunitFagor");
		s.add("JunitFalcon");
		s.add("JunitFamily Games");
		s.add("JunitFamily Games Inc.");
		s.add("JunitFamily Guy");
		s.add("JunitFamous Trails");
		s.add("JunitFan Mats");
		s.add("JunitFancy Nancy");
		s.add("JunitFanny Wang");
		s.add("JunitFanstel");
		s.add("JunitFantom");
		s.add("JunitFantom Drives");
		s.add("JunitFarberware");
		s.add("JunitFargo");
		s.add("JunitFascinations");
		s.add("JunitFashion Angels");
		s.add("JunitFashion Bed");
		s.add("JunitFat Cat");
		s.add("JunitFat Gecko");
		s.add("JunitFellowes");
		s.add("JunitFender");
		s.add("JunitFender®");
		s.add("JunitFenixLight");
		s.add("JunitFeral");
		s.add("JunitFeral Interactive");
		s.add("JunitFidek");
		s.add("JunitFidelity Electronics");
		s.add("JunitFierce Audio");
		s.add("JunitFierce Car Audio");
		s.add("JunitFiesta");
		s.add("JunitFilemaker");
		s.add("JunitFilterStream");
		s.add("JunitFiltrete");
		s.add("JunitFind It");
		s.add("JunitFind It Games");
		s.add("JunitFindables");
		s.add("JunitFindingKing");
		s.add("JunitFinis");
		s.add("JunitFinishing Touch");
		s.add("JunitFinley Home");
		s.add("JunitFire Sense");
		s.add("JunitFireKing");
		s.add("JunitFirefield");
		s.add("JunitFirefly");
		s.add("JunitFirefly Books");
		s.add("JunitFirestik");
		s.add("JunitFirst & Main");
		s.add("JunitFirst Alert");
		s.add("JunitFisher-Price");
		s.add("JunitFishman");
		s.add("JunitFiskars");
		s.add("JunitFitbit");
		s.add("JunitFlash Frame");
		s.add("JunitFlashlogic");
		s.add("JunitFlight Form");
		s.add("JunitFlip Video");
		s.add("JunitFlipbac");
		s.add("JunitFlo Digital");
		s.add("JunitFloto");
		s.add("JunitFluke Networks");
		s.add("JunitFlyzone");
		s.add("JunitFoamheads");
		s.add("JunitFocal");
		s.add("JunitFocus Ear");
		s.add("JunitFocus Electrics");
		s.add("JunitFocus Electronics");
		s.add("JunitFocusrite");
		s.add("JunitFoodSaver");
		s.add("JunitFor Dummies");
		s.add("JunitForces of Valor");
		s.add("JunitForemost");
		s.add("JunitForever Collectibles");
		s.add("JunitFort Bryan");
		s.add("JunitFortress");
		s.add("JunitForum");
		s.add("JunitForward Industries");
		s.add("JunitFoscam");
		s.add("JunitFosmon");
		s.add("JunitFosom");
		s.add("JunitFostex");
		s.add("JunitFox");
		s.add("JunitFox Run");
		s.add("JunitFoxconn");
		s.add("JunitFoxmind");
		s.add("JunitFractal Design");
		s.add("JunitFractiles");
		s.add("JunitFramus");
		s.add("JunitFrancine Collection");
		s.add("JunitFranklin");
		s.add("JunitFranklin Electronic Publishers");
		s.add("JunitFranklin Sports");
		s.add("JunitFranklin Wireless");
		s.add("JunitFreecom");
		s.add("JunitFrends");
		s.add("JunitFreud");
		s.add("JunitFrieling");
		s.add("JunitFrigidaire");
		s.add("JunitFrigidaire Professional");
		s.add("JunitFrommer s");
		s.add("JunitFrommer's");
		s.add("JunitFrommers");
		s.add("JunitFront Porch Classics");
		s.add("JunitFroth Au Lait");
		s.add("JunitFruwt");
		s.add("JunitFuel Doctor");
		s.add("JunitFuji");
		s.add("JunitFujifilm");
		s.add("JunitFujitsu");
		s.add("JunitFulham-Frills & Access");
		s.add("JunitFull Spectrum");
		s.add("JunitFun Furnishings");
		s.add("JunitFun-World");
		s.add("JunitFundex Games");
		return s;
	}
}
